<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="EnergrTest._Default" %>
<html>
<head runat="Server">
	<title></title>
</head>
<body>
	<form id="form1" runat="Server">
		<div>
			<h1 style = "background-color :Aqua"; align="center" > Welcome </h1>
			
	<table>
				<tr>
					<td> Enter Date </td>
					<td>
						<asp:TextBox ID="txtDate" runat="Server"></asp:TextBox>

					</td>
				</tr>
				<tr>
					<td> Energy Type </td>
					<td>
						<asp:DropDownList ID="DropDownList1" runat="server" >
							<asp:ListItem Value="Electricity"></asp:ListItem>
							<asp:ListItem Value="Gas"></asp:ListItem>
						</asp:DropDownList>

					</td>
				</tr>
				<tr>
					<td> Prise in $</td>
					<td>
						<asp:TextBox ID="txtPrise" runat="Server"></asp:TextBox>

					</td>
				</tr>
	<tr>
	<td colspan="2" align="center" >
		<asp:Button ID="Button1" runat="server" Text="Enter" OnClick="Button1_Click" /> </td>
	</tr>
	</table>
			</div>
		<br />
		<br />





		<asp:GridView ID="GridView1" runat="server"
		     OnRowDeleting="GridView1_RowDeleting"
			onselectedindexchanged="GridView1_SelectedIndexChanged1" AutoGenerateDeleteButton="True">
		</asp:GridView>

		</form>
	</body>
</html>
